### ISSUE TITLE
Localization problems

### ISSUE THREAD

**Issue by Raider472** [YummYume/Russia-2.0#34]
Localization events :

- [x] soviets.29 : changer l'image
- [x] soviets.42 : tooltips pour changer les options qui affichent les statistiques (comme pour les révoltes Ukraine)(ex : "Low chance for the Ukrainian revolt to happen")
- [x] soviets.46 : la description fait un peu gamin ou elle me semble un peu "rush"
- [x] soviets.59 : une meilleur description car elle n'est pas ouf d'après moi
- [x] soviets.63(64-65) : une meilleur description probablement
- [x] soviets.76 : une description
- [x] soviets.80 : description (les habitants avaient le droit de tenir des magasins locaux ?)
- [x] soviets.87-88: Une petite description
- [x] generics.4 : une petite description
- [x] germanys.1 : pas un problème de loca mais un truc que j'ai découvert au pif : si la russie est en guerre civile et que l'allemagne accepte la paix. L'Allemagne prend tous le territoire que les Soviets (originale) contrôlé (même si c'est pas en Europe ) et les Soviets annexe les rebelles (les mecs qui ont déclenché la guerre civile) (si tu comprend pas, juste lance l'event de la paix de l'Allemagne pendant que les soviets sont en guerre civile)
- [x] newsrussia2.15 : description, petit detail mais je ne pense pas que les paysans pouvaient quitter la Russie (mais bon osef) 
- [x] newsrussia2.29 : description 
- [x] newsrussia2.30 : description 
- [x] newsrussia2.31 : description 
- [x] newsrussia2.32 : description 
- [x] newsrussia2.33 : description 
- [x] newsrussia2.34 : description 
- [x] newsrussia2.38 : toute la loca à faire
- [x] newsrussia.39 : Toute la loca à faire ou le supprimer
- [x] newsrussia.44-47 : check si la description est bonne
- [x] reste des newsrussia : loca
- [x] besoin d'un world event pour les l'invitation des révolutions
- [x] Yaltas.1 : description
- [x] yaltas.7 : description
- [x] yaltas.8 : description
- [x] yaltas.9 : description
- [x] yaltas.10 : description

**Comment by YummYume** [comment]
All the localization has been greatly improved
