### ISSUE TITLE
Russian Fascist Path

### ISSUE THREAD

**Issue by Ganon421** [YummYume/Russia-2.0#44]
The Russian Fascist Path has an issue when you use go down the "Order" side instead of law. Upon finishing "Outside Question" the focus "Italian Embassy" was bypassed making it impossible for Italy to get the decision for an alliance. I switched tags and had the Russians do the "Outside Question" and did not get any event.

**Comment by YummYume** [comment]
@Ganon421 Have you checked why the focus bypassed? It will get bypassed if : Italy doesn't exist, is Communist, is a subject, is at war with you, you have chosen to focus on Europe, you do not have Alliance with Europe or Closed Alliance (as a result of "The Outside Question" focus.
